### ISSUE TITLE
Extend get_feed to handle pagination

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/C-3PO#1]
Currently, [`get_feed`](https://github.com/lttkgp/C-3PO/blob/master/c3po/core.py#L47) fetches only the first page. To learn more about how pagination works in the Graph API, check out their documentation at https://developers.facebook.com/docs/graph-api/using-graph-api/#paging.

To start with, fetch all posts until the very first by following the pagination links returned by the API. This is needed to populate our db (when we have one).

**Comment by KumarRishabh** [comment]
I have send a PR probably fixing this issue.

**Comment by ghostwriternr** [comment]
Completed in #7
