### ISSUE TITLE
Create get_post

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/C-3PO#2]
Add a method `get_post` to use the `id` from each post in `get_feed` to fetch the following information:
- Created time
- Message
- Message tags
- From
- Link
- Shares
- To
- Updated time

Information regarding these fields can be found here: https://developers.facebook.com/docs/graph-api/reference/v2.11/post

**Comment by sladyn98** [comment]
Hey i would like to work on this issue. Can you help me how to get started.

**Comment by ghostwriternr** [comment]
The link I have provided should give you a hint on getting started.

**Comment by KumarRishabh** [comment]
I want to take up this issue.

**Comment by sladyn98** [comment]
Im working on it actually

**Comment by KumarRishabh** [comment]
@ghostwriternr do we need to fetch information about "to" ? Posts are directed to the group, right ?

**Comment by ghostwriternr** [comment]
Done in dddbff8
