### ISSUE TITLE
Extend get_post to fetch likes and comments

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/C-3PO#3]
Once #2  is complete, extend get_post to get information about users who have reacted to the post (and what reaction) and the comments on the post.

From the comments in each post, it is only required to find any links posted by other users. If so, maintain them in the object. (Storing this data can be handled later) It is not necessary to maintain the 'comment' -> 'comment reply' hierarchy. It is okay to keep all links simply as a list of 'children' (say).

**Comment by aditodkar** [comment]
I will work on this.

**Comment by ghostwriternr** [comment]
Closing as obsolete.
