### ISSUE TITLE
 Enable hot-reloading Docker dev setup

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/C-3PO#84]
Currently, during development, the Docker image needs to be rebuilt every time there is a change, which slows down testing. Hot reloading would make this a lot smoother. This is quite trivial - fun fix for first-timers.
Tutorial: https://stackoverflow.com/a/44344442/4396392

**Comment by malathit** [comment]
Shall I take this up for **Hacktoberfest**?

**Comment by ghostwriternr** [comment]
Hi @malathit ! Sure : ) Looking forward to your PR.

**Comment by malathit** [comment]
Hey I just looked at the code. It looks like you are already mounting the directory to the docker container in docker-compose. I am not sure if you have enabled the debugging for the flask app. Can you be brief of what exactly to be done?

**Comment by ghostwriternr** [comment]
@malathit you're right indeed about the mount point. But if you try running the service locally, you can see it in itself isn't enough. Currently, the Dockerfile we use is set-up to use `wsgi` (which runs Flask in production mode). But during local development, we'd like to bypass `wsgi` and run flask in development mode.

So, this task would entail:
- Writing a modified `Dockerfile.dev` (most of which would be the same as the current `Dockerfile`) that starts the C-3PO flask server in development mode with debug mode enabled
- Modifying the docker-compose file (which is fine since we only use it in development for now) to use the newly written `Dockerfile.dev`
