### ISSUE TITLE
Add a pre-commit hook to run sanity.sh

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/C-3PO#91]
A pre-commit hook can be set up to run any command/script before changes are committed. Running [sanity.sh](https://github.com/lttkgp/C-3PO/blob/2182f76d510c07c650964aad6e811cdf7db49a83/bin/sanity.sh) as a pre-commit hook would ensure all commits/PRs are properly formatted, as expected by the project.

**Comment by 2000yeshu** [comment]
I would like to give it a try.
